# Modern Methods for Text Classification

In [1]:
# if you are using the fastAI environment, all of these imports work
import gzip
import os
from tqdm import tqdm
from urllib.request import urlretrieve
from pathlib import Path
import numpy as np
import pandas as pd

In [2]:
import spacy
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer

In [3]:
class TqdmUpTo(tqdm):
    def update_to(self, b=1, bsize=1, tsize=None):
        if tsize is not None: self.total = tsize
        self.update(b * bsize - self.n)

def get_data(url, filename):
    """
    Download data if the filename does not exist already
    Uses Tqdm to show download progress
    """
    if not os.path.exists(filename):

        dirname = os.path.dirname(filename)
        if not os.path.exists(dirname):
            os.makedirs(dirname)

        with TqdmUpTo(unit='B', unit_scale=True, miniters=1, desc=url.split('/')[-1]) as t:
            urlretrieve(url, filename, reporthook=t.update_to)

In [4]:
# Let's download some data:
data_url = 'http://files.fast.ai/data/aclImdb.tgz'
get_data(data_url, 'data/imdb.tgz')
# Manually extract the files above - your extractor depends on your Operating System. I used 7z on Windows and dtrx on Linux-Ubuntu16.04LTS. 

In [5]:
data_dir = !pwd 
data_dir = Path(data_dir[0])/'data'/'imdb'/'aclImdb'
assert data_dir.exists()
for pathroute in os.walk(data_dir):
    next_path = pathroute[1]
    for stop in next_path:
        print(stop)

test
train
pos
all
neg
unsup
pos
all
neg


# Read data into separate dataframes/strings

In [6]:
train_path = data_dir/'train'
test_path = data_dir/'test'
assert train_path.exists()
assert test_path.exists()

In [7]:
def load_data(dir_path):
    
    def load_dir_reviews(reviews_path):    
        files_list = list(reviews_path.iterdir())
        reviews = []
        for filename in files_list:
            f = open(filename, 'r', encoding='utf-8')
            reviews.append(f.read())
        return pd.DataFrame({'text':reviews})
        
    
    pos_path = dir_path/'pos'
    neg_path = dir_path/'neg'
    pos_reviews, neg_reviews = load_dir_reviews(pos_path), load_dir_reviews(neg_path)
    pos_reviews['label'] = 1
    neg_reviews['label'] = 0
    merged = pd.concat([pos_reviews, neg_reviews])
    merged.reset_index(inplace=True)
    return merged

In [8]:
%time
train = load_data(train_path)
test = load_data(test_path)
X_train, y_train = train['text'], train['label']
X_test, y_test = test['text'], test['label']

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 6.68 µs


## Logistic Regression

In [9]:
from sklearn.linear_model import LogisticRegression as LR

In [10]:
lr_clf = Pipeline([('vect', CountVectorizer()), ('tfidf', TfidfTransformer()), ('clf',LR())])

In [11]:
%%time
lr_clf.fit(X=X_train, y=y_train)
lr_predicted = lr_clf.predict(X_test)
lr_acc = sum(lr_predicted == y_test)/len(lr_predicted)
print(lr_acc)

0.88312
CPU times: user 21.5 s, sys: 748 ms, total: 22.3 s
Wall time: 11.5 s


**Let's  keep another model for reference**

In [12]:
lr_clf2 = Pipeline([('vect', CountVectorizer(ngram_range=(1,3))), ('tfidf', TfidfTransformer()), ('clf',LR())])
lr_clf2.fit(X=X_train, y=y_train)

Pipeline(memory=None,
     steps=[('vect', CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 3), preprocessor=None, stop_words=None,
        strip...ty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False))])

In [13]:
lr2_predicted = lr_clf2.predict(X_test)
lr2_acc = sum(lr2_predicted == y_test)/len(lr_predicted)
print(lr2_acc)

0.87752


# Multinomial Naive Bayes

Note: Why is the above called Naive? There are more powerful and complex methods involving Bayesian approaches. 

In [14]:
from sklearn.naive_bayes import MultinomialNB as MNB

**Keeping the best performing model from Previous**

In [15]:
mnb_clf = Pipeline([('vect', CountVectorizer(stop_words='english', ngram_range=(1,3))), ('tfidf', TfidfTransformer()), ('clf',MNB())])

In [16]:
mnb_clf.fit(X=X_train, y=y_train)
mnb_predicted = mnb_clf.predict(X_test)
sum(mnb_predicted == y_test)/len(y_test)

0.8572

## Extra Trees Classifier 

**Keeping the best performing model from Previous**

In [17]:
from sklearn.ensemble import ExtraTreesClassifier as XTC
xtc_clf = Pipeline([('vect', CountVectorizer()), ('tfidf', TfidfTransformer()), ('clf',XTC())])

In [18]:
xtc_clf.fit(X=X_train, y=y_train)
xtc_predicted = xtc_clf.predict(X_test)
sum(xtc_predicted == y_test)/len(y_test)

0.74224

# Ensemble Models 
**Ensembling models** is a very powerful technique to improve your model performance across a variety of Machine Learning tasks. 

In the section below, I borrow heavily from the [Kaggle Ensembling Guide](https://mlwave.com/kaggle-ensembling-guide/) written by [MLWave](https://mlwave.com/).

I explain why ensembling helps reduce error, or improve accuracy. I demonstrate all the popular techniques on our chosen task and dataset. Each demo includes the ensembling code (borrowed from MLWave) and performance gain from those. 

To ensure that you understand these techniques, I strongly urge you to try them on a few datasets. 

## Voting Ensemble

### Simple Majority
The simplest ensembling technique is perhaps to take a simple majority. This works on the intuition that a single model might make a error on a particular prediction, but several different models are unlikely to make identical errors. 

Let's look at an example. 

Ground truth: 1**1**011001

Let's assume there are 3 models with only one error for this example

Model A Prediction: 1**0**011001

Model B Prediction: 1**1**011001

Model C Prediction: 1**1**011001

The majority votes gives us the correct answer in this example - 

Majority vote: 1**1**10110011

---

We have predictions from our models above, let's check the first few predictions from each of those: 

In [19]:
samples = 20
xtc_predicted[:samples], mnb_predicted[:samples], lr_predicted[:samples]

(array([1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))

We notice that the predictions don't agree with each other even on the first few samples. Let's write a function to take a simple majority prediction. 

In [20]:
def voting(predictions, style="majority"):
    count_p = len(predictions)  # number of predictions
    assert count_p > 1
    return np.asarray([int(x) for x in sum(predictions) > count_p // 2])

In [21]:
predictions = [lr_predicted, lr2_predicted, mnb_predicted]

In [22]:
simple_majority = voting(predictions)
sum(simple_majority == y_test)/len(y_test)

0.88596

We get an improvement from our simple ensembling technique but nothing significant. Why would this be?

#### Understanding Correlations

To see this, let us take 3 simple models again. The ground truth is all 1’s:

1111111100 = 80% accuracy

1111111100 = 80% accuracy

1011111100 = 70% accuracy

These models are highly correlated in their predictions. When we take a majority vote we see no improvement:

1111111100 = 80% accuracy

Now we compare to 3 less-performing, but highly uncorrelated models:

1111111100 = 80% accuracy

0111011101 = 70% accuracy

1000101111 = 60% accuracy

When we ensemble this with a majority vote we get:

1111111101 = 90% accuracy

We get an improvement which is much higher than any of our individual models. Low correlation between model predictions can lead to better performance. 

In [23]:
np.corrcoef(lr2_predicted, lr_predicted)[0][1]

0.884381372740408

In [24]:
np.corrcoef(mnb_predicted, lr_predicted)[0][1]

0.7859628207349088

In [25]:
np.corrcoef(xtc_predicted, lr_predicted)[0][1]

0.5357472161807284

In [26]:
np.corrcoef(xtc_predicted, mnb_predicted)[0][1]

0.5223665147040992

In [27]:
np.corrcoef(xtc_predicted, lr2_predicted)[0][1]

0.5324490457674085

In [28]:
predictions = [mnb_predicted, mnb_predicted, xtc_predicted]

In [29]:
uncorrelated_majority = voting(predictions)
sum(uncorrelated_majority == y_test)/len(y_test)

0.8572

In [30]:
predictions = [lr_predicted, lr_predicted, lr2_predicted, mnb_predicted, xtc_predicted]

In [31]:
weighted_majority = voting(predictions)
sum(weighted_majority == y_test)/len(y_test)

0.88484